color: null
fieldLayouts:
  c1805f47-7d20-47d4-8ae0-99427a38111c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-03T11:54:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c69ae4d9-9663-40c1-ab14-bf600cda66c3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 764fa209-1710-4061-adde-b5507d3af420
        userCondition: null
handle: entBuildings
hasTitleField: true
icon: building
name: 'Ent Buildings'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
