color: null
fieldLayouts:
  0309ad3a-9996-45ae-8320-9783e3b258ec:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-03T12:19:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'First Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f3cf744a-5f97-4ae2-bdab-5dc600b4f38b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-03T12:21:38+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2327a6f6-417b-4334-b051-5d9d0a4d5c02 # Plain Text
            handle: fd_surname
            includeInCards: false
            instructions: null
            label: Surname
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed5a6c88-1539-4eb5-852a-ea9a60a0a994
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 35320e1e-edb6-451c-b9d7-0c1328ea899c
        userCondition: null
handle: entSupervisors
hasTitleField: true
icon: clipboard
name: 'Ent Supervisors'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
