color: null
fieldLayouts:
  36442561-db6c-4d0a-9af8-57caa6ae6875:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-05-04T15:50:56+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9130a574-e4da-41e6-8c18-d8489699e6b4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eba244e0-5462-4663-ad73-985abf92dc5d
        userCondition: null
handle: entTasks
hasTitleField: true
icon: check
name: 'ENT Tasks'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
