columnSuffix: null
handle: mxDepartments
instructions: null
name: Departments
searchable: false
settings:
  createButtonLabel: 'Add Department'
  defaultIndexViewMode: cards
  enableVersioning: false
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
