dateModified: 1746274903
email:
  fromEmail: access@hypha.media
  fromName: 'Porter Craft'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0ddc1c53-595b-487f-8473-eece2e4861de: 'Ent Supervisors' # Ent Supervisors
    5f52388b-f9f4-4132-81c1-55802c67d8cc: Buildings # Buildings
    6a92aa12-7350-4d77-a9af-a478cee25845: 'Porter Craft' # Porter Craft
    2327a6f6-417b-4334-b051-5d9d0a4d5c02: 'Plain Text' # Plain Text
    a6ca13d7-bc6b-4c17-a310-b0fcaa34804d: 'Ent Buildings' # Ent Buildings
    b1d95329-57ac-49cf-90d7-b40a1bdbcd01: Porters # Porters
    ceac8342-76fb-422f-a0a3-efb6a2e94704: Departments # Departments
    ebb3dbd8-552b-48fb-aebb-0c13143be157: 'Porter Craft' # Porter Craft
    f44b07d1-48b3-48fe-8bfe-f8f12f5ed053: Supervisors # Supervisors
    f5051ed3-2649-4f41-a303-9d3b06368f94: 'Ent Departments' # Ent Departments
    fe915955-f57d-4ec4-bf9c-92c417a8e11d: 'Ent Porters' # Ent Porters
system:
  edition: solo
  live: true
  name: 'Porter Craft'
  schemaVersion: 5.7.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
