defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: a77bbb05-d771-4014-ae5a-7e0b5e8be34b # Ent Departments
  -
    uid: a6ca13d7-bc6b-4c17-a310-b0fcaa34804d # Ent Locations
handle: locations
maxAuthors: 1
name: Locations
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6a92aa12-7350-4d77-a9af-a478cee25845: # Porter Craft
    enabledByDefault: true
    hasUrls: true
    template: buildings/_entry.twig
    uriFormat: 'buildings/{slug}'
structure:
  maxLevels: 2
  uid: f45aa08e-b7fb-4c84-9451-139a3f043937
type: structure
