defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1fefe862-852d-49ba-83cb-906b289365ac # ENT Tasks
  -
    uid: a029653d-b401-4157-b33a-c398463b10b2 # Task Categories
handle: taskCategories
maxAuthors: 1
name: 'Task Categories'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6a92aa12-7350-4d77-a9af-a478cee25845: # Porter Craft
    enabledByDefault: true
    hasUrls: true
    template: task-types/_entry.twig
    uriFormat: 'task-types/{slug}'
structure:
  maxLevels: 2
  uid: 6d82f239-d875-460d-9894-247138a60268
type: structure
